name: Release

on: push

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
#        with:
#          node-version: 12
#          registry-url: 'https://registry.npmjs.org'
#      - run: npm install
#      - run: npm publish
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: actions/checkout@v2
      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CSSA1Y }}'
          projectId: cssa1y
          channelId: 'pr-${{ github.event.number }}-${{ github.event.pull_request.head.ref }}'