name: Release

on: push

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  deployexample:
      name: Deploy Example in firebase
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@master
        - uses: actions/setup-node@master
          with:
            node-version: 12
        - run: "npm install"
          working-directory: ./example
        - uses: w9jds/firebase-action@master
          with:
            args: deploy --only hosting
          env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}